org: jhouse153
app: auth
service: auth-api

package:
  individually: true
useDotenv: true
plugins:
  - serverless-bundle
  - serverless-offline
  #- serverless-dotenv-plugin

custom:
  bundle:
    linting: false
    disableForkTsChecker: true
    ignorePackages:
      - pg-native
  serverless-offline:
    httpPort: 3001
    stageVariables:
      foo: 'bar'

provider:
  name: aws
  region: us-east-1
  memorySize: 256
  profile: jpurdie
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  apiName: auth-api
  logRetentionInDays: 3
  lambdaHashingVersion: 20201221
  httpApi:
    authorizers:
      gcpIdpAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://securetoken.google.com/${env:GCP_IDP_PROJECT}
        audience:
          - ${env:GCP_IDP_PROJECT}

functions:
  publicEndpointGet:
    handler: functions/public/get.default
    runtime: nodejs14.x
    events:
      - httpApi:
          path: /api/v1/public/{idreq}
          method: GET
      - httpApi:
          path: /api/v1/public/
          method: GET
  publicEndpointPost:
    handler: functions/public/post.default
    runtime: nodejs14.x
    events:
      - httpApi:
          path: /api/v1/public/{idreq}
          method: POST
    environment:
  privateEndpoint:
    handler: functions/private/private.default
    runtime: nodejs14.x
    environment:
    events:
      - httpApi:
          path: /api/v1/private
          method: get
          authorizer:
            name: gcpIdpAuthorizer
